//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cao.WMS.Web.caowms.Users {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblUID;
		protected global::System.Web.UI.WebControls.TextBox txtUPassword;
		protected global::System.Web.UI.WebControls.TextBox txtUPower;
		protected global::System.Web.UI.WebControls.TextBox txtUSex;
		protected global::System.Web.UI.WebControls.TextBox txtUName;
		protected global::System.Web.UI.WebControls.TextBox txtUAddress;
		protected global::System.Web.UI.WebControls.TextBox txtUTel;
		protected global::System.Web.UI.WebControls.TextBox txtUEmail;
		protected global::System.Web.UI.WebControls.TextBox txtUDep;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
