//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cao.WMS.Web.caowms.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUID;
	protected global::System.Web.UI.WebControls.Label lblUPassword;
	protected global::System.Web.UI.WebControls.Label lblUPower;
	protected global::System.Web.UI.WebControls.Label lblUSex;
	protected global::System.Web.UI.WebControls.Label lblUName;
	protected global::System.Web.UI.WebControls.Label lblUAddress;
	protected global::System.Web.UI.WebControls.Label lblUTel;
	protected global::System.Web.UI.WebControls.Label lblUEmail;
	protected global::System.Web.UI.WebControls.Label lblUDep;


       
    }
}
